# Generated by Django 5.2.5 on 2025-08-31 17:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChestXRayImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='chest_xrays/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('prediction', models.CharField(choices=[('normal', 'Normal'), ('pneumonia', 'Pneumonia'), ('pending', 'Pending Analysis')], default='pending', max_length=20)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('pneumonia_type', models.CharField(choices=[('bacterial', 'Bacterial Pneumonia'), ('viral', 'Viral Pneumonia'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('analysis_date', models.DateTimeField(blank=True, null=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Chest X-Ray Image',
                'verbose_name_plural': 'Chest X-Ray Images',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
